// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbGitKDTqFhxCnfSbxyE9are-BMpuLvjU',
    appId: '1:497080096855:web:45fe3f511532c8f2296b12',
    messagingSenderId: '497080096855',
    projectId: 'redcellnet-8a35e',
    authDomain: 'redcellnet-8a35e.firebaseapp.com',
    storageBucket: 'redcellnet-8a35e.firebasestorage.app',
    measurementId: 'G-V8BVCB8FH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeyKtEEjazaA9X1K5rHLfoJu1GfAjU0s4',
    appId: '1:497080096855:android:2d0513abd9447e89296b12',
    messagingSenderId: '497080096855',
    projectId: 'redcellnet-8a35e',
    storageBucket: 'redcellnet-8a35e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPuT320sbna_-kC2BApZlD9txenDb3AiY',
    appId: '1:497080096855:ios:9b9090a3791e8a87296b12',
    messagingSenderId: '497080096855',
    projectId: 'redcellnet-8a35e',
    storageBucket: 'redcellnet-8a35e.firebasestorage.app',
    iosBundleId: 'com.example.redCellNet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPuT320sbna_-kC2BApZlD9txenDb3AiY',
    appId: '1:497080096855:ios:9b9090a3791e8a87296b12',
    messagingSenderId: '497080096855',
    projectId: 'redcellnet-8a35e',
    storageBucket: 'redcellnet-8a35e.firebasestorage.app',
    iosBundleId: 'com.example.redCellNet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbGitKDTqFhxCnfSbxyE9are-BMpuLvjU',
    appId: '1:497080096855:web:44e983fbec197807296b12',
    messagingSenderId: '497080096855',
    projectId: 'redcellnet-8a35e',
    authDomain: 'redcellnet-8a35e.firebaseapp.com',
    storageBucket: 'redcellnet-8a35e.firebasestorage.app',
    measurementId: 'G-91FGQDWCZT',
  );

}